repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-yaml

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: templates/
        args:
          - --line-length=120

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        exclude: templates/
        args:
          - column_limit=120
          - use_tabs=True
          - continuation_indent_width=4
          - blank_line_before_nested_class_or_def=True

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^demucs/
        args:
          - --max-line-length=120
          - --ignore=W605, W292, F401
